# Generated by Django 2.2.6 on 2020-05-09 23:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PentestScanModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, unique=True, verbose_name='название теста')),
                ('site_ip', models.CharField(blank=True, max_length=32, verbose_name='ip сайта')),
                ('scan_type', models.CharField(blank=True, choices=[('', 'Вектор атаки'), ('Сканирование сетки', 'Сканирование сетки'), ('Брут  директорий', 'Брут  директорий'), ('DOS атака', 'DOS атака'), ('Сканирование на узявимости', 'Сканирование на узявимости')], max_length=250, verbose_name='вектор атаки')),
            ],
            options={
                'verbose_name': 'Pentest',
                'verbose_name_plural': 'Pentests',
            },
        ),
    ]
