# Generated by Django 2.2.6 on 2020-05-11 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vulns-scan', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PentestScanModel',
            new_name='PentestModel',
        ),
    ]
