# Generated by Django 2.2.6 on 2020-05-11 00:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vulns-scan', '0002_auto_20200511_0021'),
    ]

    operations = [
        migrations.CreateModel(
            name='PentestScanModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, unique=True, verbose_name='название теста')),
                ('site_ip', models.CharField(blank=True, max_length=32, verbose_name='ip сайта')),
                ('scan_type', models.CharField(blank=True, choices=[('', 'Вектор атаки'), ('Сканирование сетки', 'Сканирование сетки'), ('Брут  директорий', 'Брут  директорий'), ('DOS атака', 'DOS атака'), ('Сканирование на узявимости', 'Сканирование на узявимости')], max_length=250, verbose_name='вектор атаки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'Pentest',
                'verbose_name_plural': 'Pentests',
            },
        ),
        migrations.DeleteModel(
            name='PentestModel',
        ),
    ]
