# Generated by Django 2.2.6 on 2020-05-11 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vulns-scan', '0003_auto_20200511_0032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pentestscanmodel',
            options={'verbose_name': 'Pentest Scan', 'verbose_name_plural': 'Pentests Scans'},
        ),
        migrations.CreateModel(
            name='PentestResultModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, unique=True, verbose_name='название теста')),
                ('site_ip', models.CharField(blank=True, max_length=32, verbose_name='ip сайта')),
                ('scan_type', models.CharField(blank=True, max_length=250, verbose_name='вектор атаки')),
                ('city', models.CharField(blank=True, max_length=250, verbose_name='город')),
                ('vulns', models.TextField(blank=True, verbose_name='Узявимости')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pentest Result',
                'verbose_name_plural': 'Pentests Results',
            },
        ),
    ]
