# Generated by Django 2.2.6 on 2020-05-11 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulns-scan', '0004_auto_20200511_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='pentestscanmodel',
            name='city',
            field=models.CharField(blank=True, max_length=250, verbose_name='город'),
        ),
        migrations.AddField(
            model_name='pentestscanmodel',
            name='vulns',
            field=models.TextField(blank=True, verbose_name='Узявимости'),
        ),
        migrations.DeleteModel(
            name='PentestResultModel',
        ),
    ]
