# Generated by Django 2.2.6 on 2020-05-18 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulns-scan', '0006_auto_20200511_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pentestmodel',
            name='vulns',
            field=models.TextField(blank=True, verbose_name='Уязвимости'),
        ),
    ]
