# Generated by Django 2.2.6 on 2020-05-18 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulns-scan', '0007_auto_20200518_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pentestmodel',
            name='scan_type',
            field=models.CharField(blank=True, choices=[('', 'Вектор атаки'), ('Сканирование сетки', 'Сканирование сетки'), ('Брут  директорий', 'Брут  директорий'), ('DOS атака', 'DOS атака'), ('Сканирование на уязвимости', 'Сканирование на уязвимости')], max_length=250, verbose_name='вектор атаки'),
        ),
    ]
