# Generated by Django 2.2.6 on 2020-05-19 05:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vulns-scan', '0008_auto_20200518_1142'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PentestModel',
            new_name='VulnScanModel',
        ),
        migrations.AlterModelOptions(
            name='vulnscanmodel',
            options={'verbose_name': 'Vuln Scan', 'verbose_name_plural': 'Vulns Scans'},
        ),
    ]
