# Generated by Django 2.2.6 on 2020-05-19 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulns-scan', '0009_auto_20200519_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vulnscanmodel',
            name='city',
            field=models.CharField(blank=True, default=None, max_length=250, verbose_name='город'),
        ),
        migrations.AlterField(
            model_name='vulnscanmodel',
            name='vulns',
            field=models.TextField(blank=True, default=None, verbose_name='Уязвимости'),
        ),
    ]
