# Generated by Django 2.2.6 on 2020-05-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulns-scan', '0010_auto_20200519_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vulnscanmodel',
            name='city',
            field=models.CharField(default=None, max_length=250, verbose_name='город'),
        ),
        migrations.AlterField(
            model_name='vulnscanmodel',
            name='vulns',
            field=models.TextField(default=None, verbose_name='Уязвимости'),
        ),
    ]
