# Generated by Django 2.2.6 on 2020-05-19 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulns-scan', '0012_auto_20200519_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vulnscanmodel',
            name='scan_type',
        ),
        migrations.AlterField(
            model_name='vulnscanmodel',
            name='city',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='vulnscanmodel',
            name='name',
            field=models.CharField(blank=True, max_length=250, unique=True, verbose_name='test name'),
        ),
        migrations.AlterField(
            model_name='vulnscanmodel',
            name='site_ip',
            field=models.CharField(blank=True, max_length=32, verbose_name='site ip'),
        ),
    ]
