# Generated by Django 2.2.6 on 2020-05-19 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulns-scan', '0013_auto_20200519_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vulnscanmodel',
            name='name',
            field=models.CharField(blank=True, max_length=250, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='vulnscanmodel',
            name='site_ip',
            field=models.CharField(blank=True, max_length=32, verbose_name='IP-адрес'),
        ),
    ]
